# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConquerReactiveSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConquerReactiveSwift
	pod 'ReactiveSwift', '~> 6.1'
  pod 'ReactiveCocoa', '~> 10.1'
  pod 'SwiftyJSON', '~> 4.0'

end
